### ISSUE TITLE
Import to penpot develop branch fails due to missing profile_id

### ISSUE THREAD

**Issue by ryanbreen** [penpot/penpot-exporter-figma-plugin#12]
I know tracking Penpot `develop` may be aggressive for testing the exporter , but it looks like recent changes broke import due to a missing `profile_id`:

```
TRACE:
 →  org.postgresql.util.PSQLException: ERROR: null value in column "profile_id" of relation "file_profile_rel" violates not-null constraint (QueryExecutorImpl.java:2676)
```

I believe the line triggering this error is https://github.com/penpot/penpot/blob/9c44cd343f8aa8417b8ec5d2b14b8000bc7e6f79/backend/src/app/rpc/commands/files/create.clj#L32

I'm not sure whether this is something that should be fixed on the Penpot side to be more forgiving or whether we need a new export of penpot.js.

**Comment by superalex** [comment]
Hmmmmmm, thank you very much for pointing it out, probably it's something that we need to fix on the Penpot side and generate a new version of penpot.js. I'll check it as soon as I can :)

**Comment by superalex** [comment]
Finally @pabloalba solved this here -> https://github.com/penpot/penpot/pull/2726 :)

Thank you very much @ryanbreen

**Comment by ryanbreen** [comment]
Thanks!  Tested and validated it's all good now.  Y'all cool 💖
