### ISSUE TITLE
Gracefully handle unmatched fonts

### ISSUE THREAD

**Issue by ryanbreen** [penpot/penpot-exporter-figma-plugin#13]
The set of fonts supported by Figma doesn't perfectly match the fonts supported out-of-the-box by Penpot.  In the attachment, the font "Jeju Gothic" reverts to a default while the other 3 import cleanly.

We need to figure out the right way to handle this, perhaps prompting the user in the plugin dialog that they'll need to add a font to Penpot before import will succeed.

[font_test.zip](https://github.com/penpot/penpot-exporter-figma-plugin/files/10325243/font_test.zip)

**Comment by ryanbreen** [comment]
(I can work on this one)

**Comment by superalex** [comment]
Hey!,

We were talking with the rest of the team about this and your idea sounds good. Thank you very very much!
