### ISSUE TITLE
Changes detected. Please reload the plugin...

### ISSUE THREAD

**Issue by clayrisser** [penpot/penpot-exporter-figma-plugin#150]
Everytime I run this plugin to try to export a figma design, I get the following error.

<img width="320" alt="Screenshot 2024-06-10 at 8 57 41 AM" src="https://github.com/penpot/penpot-exporter-figma-plugin/assets/6234038/3dc068b2-8cba-455c-b51f-e06a4c80f4ae">

Here is a link to the tamagui design I'm trying to export.

https://www.figma.com/community/file/1326593766534421119/tamagui-v1-2-1

**Comment by jordisala1991** [comment]
Hi!, Do you execute the plugin and click to the export button? This window you are showing only appears when you are modifying the design while the plugin is open

**Comment by clayrisser** [comment]
I execute the plugin and click the export button. It takes a long time to run, but I do not modify the project while it's running. I've tried this 5 times, with the exact same results.

Can you confirm from your end if it's doing that with the following project?

https://www.figma.com/community/file/1326593766534421119/tamagui-v1-2-1

**Comment by clayrisser** [comment]
Turns out it's working. The file gets downloaded even though I get that message.

**Comment by jordisala1991** [comment]
With the latest release, the reload message should appear way less... ideally only when it is really needed :)
