### ISSUE TITLE
 Problems Exporting Figma Components Using Penpot Exporter Plugin

### ISSUE THREAD

**Issue by Lavanya881** [penpot/penpot-exporter-figma-plugin#161]
We are encountering several issues while exporting Figma components to Penpot using the Penpot Exporter plugin. The problems are as follows:

1.Component Corruption:  The exported components are getting corrupted during the export process.

2.Missing Content:  Only the outlines of the components are being imported into Penpot, with the main content missing.

3.Performance Issues:  The export process from Figma and the import process to Penpot are both taking an excessively long time.
![WhatsApp Image 2024-06-13 at 15 35 19](https://github.com/penpot/penpot-exporter-figma-plugin/assets/126563974/2ec31fae-725a-4ffc-8939-39683ba3760e)
![WhatsApp Image 2024-06-13 at 15 37 16](https://github.com/penpot/penpot-exporter-figma-plugin/assets/126563974/362a4a10-3584-4178-a70b-740472da1485)

These issues are significantly impacting our workflow. Kindly resolve these issues at the earliest.

Thank you!

**Comment by Cenadros** [comment]
Hi there @Lavanya881 ,

Could you please provide us with an example of figma file in which you're encountering this issues so we can further investigate it?

Thank you!
