### ISSUE TITLE
Unable to export Figma design

### ISSUE THREAD

**Issue by the3dfox** [penpot/penpot-exporter-figma-plugin#206]
When I try to export an existing design, the process is stuck at the last step "Generating Penpot file" and the browser console shows this error. The design is nothing special, just some layouts and filled elements. I started deleting elements until the export was sucessful. The elements which caused the problem was just a simple layout container:

![image](https://github.com/penpot/penpot-exporter-figma-plugin/assets/84663901/23eace70-539a-4c63-8ea8-7e6d109518d8)

this is the error log from the browser console

```
VM903:136 Uncaught Error: nth not supported on this type class hn{constructor(tn){tn&&(this._subscribe=tn)}subscribe(tn){return tn=tn instanceof nn?tn:new nn(tn),tn.add(this._trySubscribe(tn)),tn}_trySubscribe(tn){try{return this._subscribe(tn)}catch(rn){tn.error(rn)}}forEach(tn){return new Promise((rn,Jn)=>{const an=new nn({next:A=>{try{tn(A)}catch(V){Jn(V),an.unsubscribe()}},error:Jn,complete:rn});this.subscribe(an)})}_subscribe(tn){}[n](){return this}pipe(...tn){return tn.reduce(m,this)}[e](){let tn,rn=!1,Jn,an=!1;const A=[],V=[],Z=On=>{for(rn=!0,Jn=On;V.length;){const[,K]=V.shift();K(On)}},yn=()=>{for(an=!0;V.length;){const[On]=V.shift();On({value:void 0,done:!0})}};return{next:()=>(tn||(tn=this.subscribe({next:On=>{if(V.length){const[K]=V.shift();K({value:On,done:!1})}else A.push(On)},error:Z,complete:yn})),A.length?Promise.resolve({value:A.shift(),done:!1}):an?Promise.resolve({value:void 0,done:!0}):rn?Promise.reject(Jn):new Promise((On,K)=>{V.push([On,K])})),throw:On=>(tn?.unsubscribe(),Z(On),Promise.reject(On)),return:()=>(tn?.unsubscribe(),yn(),Promise.resolve({value:void 0,done:!0})),[Symbol.asyncIterator](){return this}}}}
    at B (<anonymous>:136:30094)
    at <anonymous>:266:12405
    at Function.r [as J] (<anonymous>:136:47707)
    at <anonymous>:138:1710
    at k.pb (<anonymous>:266:102318)
    at Vn (<anonymous>:136:34665)
    at bT (<anonymous>:138:1680)
    at Vwn (<anonymous>:266:12379)
    at <anonymous>:266:22776
    at <anonymous>:238:85241
```

link to file: https://www.figma.com/design/Qk3btoCmVEK7zBhXoGPZ8a/Untitled?node-id=0-1&t=O7qmAFVSAtL6zrSa-1

**Comment by Cenadros** [comment]
Hi there @the3dfox. Apparently something changed in the penpot lib with the .zip file generation so we made a rollback of the lib while we check on that.

We updated the plugin and now it should work.

I'm closing this issue because I've tried your document with this new version and it works.

Thank you!

**Comment by Maxborland** [comment]
Hi! Encountered same error, but when importing .penpot file successfully exported by this plugin:

<img width="541" height="272" alt="Image" src="https://github.com/user-attachments/assets/d71920ca-c151-421e-95db-873a362a4a68" />

nth not supported on this type function(a,b,c,d){this.meta=a;this.xa=b;this.ta=c;this.__hash=d;this.W=16647951;this.ba=401412}
