### ISSUE TITLE
Broken links in Figma plugin description

### ISSUE THREAD

**Issue by zcraber** [penpot/penpot-exporter-figma-plugin#212]
Under the section **How to use the plug-in**, links to `How to export/import files from Figma to Penpot` and `How to export design systems (libraries)` are broken, leading to `Create new page` in Wiki.

![image](https://github.com/user-attachments/assets/d172da6f-ed06-4915-8708-13a72cfb3fc6)

**Comment by Cenadros** [comment]
Thank you for reporting this. We've fixed the links.
