### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by KaelWD** [penpot/penpot-exporter-figma-plugin#218]
![Screenshot_20240916_225708](https://github.com/user-attachments/assets/55cd5178-d040-49ee-a572-7fbc9e7eac11)

I narrowed it down to this complex vector being masked by another vector: https://www.figma.com/design/MbjQcYTJGofGlpXSlq8itY/Broken-export?m=auto&t=2Y6boyuIKJdfuK2h-1

**Comment by Cenadros** [comment]
Hi there @KaelWD,

Thanks for the report, this issue should be solved as soon as we merge the https://github.com/penpot/penpot-exporter-figma-plugin/pull/220 PR.
