### ISSUE TITLE
`README` says license is MPL-2.0 but `LICENSE` is MIT

### ISSUE THREAD

**Issue by naltun** [penpot/penpot-exporter-figma-plugin#22]
As the title states, the accompanied `LICENSE` is MIT but `README` says the license is MPL-2.0. FWIW, MPL-2.0 is my preferred FOSS license.

**Comment by pabloalba** [comment]
Ops! Thank you!

I've just fixed it :)

**Comment by naltun** [comment]
:rocket: glad to see the MPL-2.0 getting more use
