### ISSUE TITLE
Support of boolean objects

### ISSUE THREAD

**Issue by nitramr** [penpot/penpot-exporter-figma-plugin#30]
Please add the support of boolean objects from Figma. I'm using a lot of boolean operations to combine or subtract base shape to new nondestructive shapes. Penpot support the same boolean operations too, but the Figma exporter ignores all those objects.

At the moment, I have to flatten all shapes in Figma to be able to import them in Penpot. But then I would lose the nondestructive structure of my icons.

**Comment by madalenapmelo-kp** [comment]
Hi @nitramr,

Thanks for reporting this issue! I just wanted to let you know that we have shared the baseline project for this plugin for the community to continue it - we have explained our approach to the penpot-exporter-figma-plugin in this [community post](https://community.penpot.app/t/figma-file-importer/1684).

We are not actively maintaining or resolving issues on this plugin, but we encourage you to contribute if and where you can :slightly_smiling_face:
