### ISSUE TITLE
Exported Penpot File Shows Blank Page When Using Figma Library Components

### ISSUE THREAD

**Issue by dharmendraboddeda** [penpot/penpot-exporter-figma-plugin#34]
## Description
I've encountered a problem with the Figma to Penpot export plugin. Specifically, when I use components from a library in Figma and export them to a Penpot file, the resulting page in Penpot is blank. This issue prevents me from using the plugin effectively for designs that rely on Figma library components.

## Steps to Reproduce
1. Create a design in Figma that includes components from a Figma library.
2. Use the Figma to Penpot export plugin to export the design to a Penpot file.
3. Open the exported Penpot file.

## Expected Behavior
The exported Penpot file should accurately reflect the design from Figma, including the components used from the Figma library.

## Actual Behavior
The Penpot page is blank, with none of the design elements visible.

## Screenshots
- Screenshot of the design in Figma: 
![2024-02-12-094235_screenshot](https://github.com/penpot/penpot-exporter-figma-plugin/assets/133015290/808aed17-6f89-4454-8230-86682d2f122e)

- Screenshot of the blank page in Penpot: 
![2024-02-12-094352_screenshot](https://github.com/penpot/penpot-exporter-figma-plugin/assets/133015290/de2689d8-3593-4774-91b8-7e738d8cbc5a)

Thank you for looking into this issue. I hope we can find a resolution soon.

**Comment by madalenapmelo-kp** [comment]
Hi @dharmendraboddeda,

Thanks for reporting this issue! I just wanted to let you know that we have shared the baseline project for this plugin for the community to continue it - we have explained our approach to the penpot-exporter-figma-plugin in this [community post](https://community.penpot.app/t/figma-file-importer/1684).

We are not actively maintaining or resolving issues on this plugin, but we encourage you to contribute if and where you can :slightly_smiling_face:

**Comment by jordisala1991** [comment]
Hi @dharmendraboddeda , This is already being worked on in: #124 #125

You can already try the dev version or wait for the next release soon :)

Closing as it should work better now. Please if you encounter more issues please open another issue (we know the components are not fully implemented, but we are getting there).
