### ISSUE TITLE
exporter fails the export assets

### ISSUE THREAD

**Issue by schalkneethling** [penpot/penpot-exporter-figma-plugin#7]
Hey All,

I tried out the exporter to create a possible library from the Open Peeps illustrations. Unfortunately, it currently fails. See the video below for steps to reproduce.

https://user-images.githubusercontent.com/10350960/197335757-5c005741-1091-418b-9ed8-d361da6fcac8.mp4

## Debug data:

https://gist.github.com/schalkneethling/bc18676f788d9b98968ccfcf73a4e52e

**Comment by pabloalba** [comment]
Hi!

I've just tried with the [this Open Peeps file](https://www.figma.com/community/file/816851875956733304) and the export process finishes without errors. The result is very bad, of course, because the export plugin doesn't support paths yet, and all the illustrations are paths.
