### ISSUE TITLE
penpot.js v0.0.1 is missing named exports for adding components, instances and colors

### ISSUE THREAD

**Issue by hinterdupfinger** [penpot/penpot-exporter-figma-plugin#8]
I tried to extend the functionality of the plugin to also include components, instances and colors but faced the limitation that their functions are not exported

it would be great if https://github.com/penpot/penpot/blob/develop/frontend/src/app/libs/file_builder.cljs would also be included in penpot.js from https://github.com/penpot/penpot/blob/6a296a3e526a2f8ea186599b79e3abd5c61eb3a5/frontend/src/app/main/data/workspace/libraries_helpers.cljs#L62 as well as https://github.com/penpot/penpot/blob/5463671db13441ba3f730a34118547d34a5a36f1/common/src/app/common/types/colors_list.cljc#L13

**Comment by myfunnyandy** [comment]
Hi, we've added your request to our backlog (https://tree.taiga.io/project/penpot/us/4521) to consider it properly. Hopefully we could help with this soon.

You can also join the conversation at [the Community post about the export plugin](https://community.penpot.app/t/export-figma-to-penpot/1684), you might find help there too.

**Comment by superalex** [comment]
Hi @hinterdupfinger 

I've added support to manage all kind of assets (colors, typographies, components and images) in penpot.js. You can check the new public API here -> https://github.com/penpot/penpot/blob/develop/frontend/src/app/libs/file_builder.cljs

Let me know if you have any doubts about how to use them! :)

Regards,
